[package]
name = "starix"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
toml = "0.8.13"
webhook = "2.1.2"
