url="https://blog.5-23.dev/p/{starix.id}/"
thumb="https://blog.5-23.dev/p/{starix.id}/thumb.jpg"
name="Asta blog"
[post]
content="@everyone `{starix.id}`가 올라왔어요!"
color="#00ff00"

[fix]
content=""
color="#ffff00"
